apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: check-pods-ready
spec:
  params:
    - name: project-name
      type: string
      description: "The OpenShift project to check"
  tasks:
    - name: check-pods-ready
      taskSpec:
        volumes:
          - name: tekton-home
            emptyDir: {}
        steps:
          - name: check-pods
            image: quay.io/openshift/origin-cli:latest
            volumeMounts:
              - name: tekton-home
                mountPath: /tekton/home
            env:
              - name: HOME
                value: /tekton/home  # ✅ Fix the $HOME environment variable
            script: |
              #!/bin/sh
              set -e
              echo "Checking pods in project: $(params.project-name)"
              
              # Ensure oc commands work with the correct home directory
              export KUBECONFIG=$HOME/.kube/config

              oc project $(params.project-name)
              oc wait --for=condition=Ready pods -l version=v1 --timeout=300s

              echo "✅ All pods are ready!"

